### PR TITLE
Edit docusaurus config and add github action [ENG-261]

### PR DESCRIPTION
**Pull request by alexdisdier**
We edit a few fields to build the sdk documentation for Github Pages. 

We then add a Github action to deploy when merging onto master.

✅ the sdks documentation is now public at https://stratumn.github.io/sdks-documentation/

I think we should add a search feature with algolia since it's public. https://docusaurus.io/docs/search#using-algolia-docsearch

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdks-documentation/4)

### CODE REVIEW

**Review by conord33 — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdks-documentation/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @azuenko and @haroldcb)

**Review by conord33 — APPROVED** [review]
can you create a ticket for the algolia thing?

> *[Reviewable](https://reviewable.io/reviews/stratumn/sdks-documentation/4#-:-Mb1EhzKC2YfaG0xN4xF:b-trqs7n)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @azuenko and @haroldcb)

**Review by conord33 — APPROVED** [review]
also just noticed, but when you click on `edit this page`, the link is broken :disappointed: 

> *[Reviewable](https://reviewable.io/reviews/stratumn/sdks-documentation/4#-:-Mb1sF1-BlGIWyz9BhJB:b-fp844g)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @azuenko and @haroldcb)

**Review by alexdisdier — COMMENTED** [review]
Sounds good. I'll create 

> *[Reviewable](https://reviewable.io/reviews/stratumn/sdks-documentation/4#-:-Mb1I14H66BOPitPCYtN:bwwtoug)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @azuenko and @haroldcb)

**Pull request merged**
