### PR TITLE
Add search pluging [ENG-268]

### PR DESCRIPTION
**Pull request by alexdisdier**
On Docusaurus documentation site, they recommend a few free plugins to make the site searchable. 

I opted for [docusaurus-lunr-search](https://www.npmjs.com/package/docusaurus-lunr-search).
- It has the most weekly downloads out of the [4 recommended](https://docusaurus.io/community/resources).
- Last published 23 days ago (seems maintained). 
- Based on [**Algolia DocSearch**](https://github.com/algolia/docsearch) tool.  

I am also thinking of adding this same plugin to our internal documentation. 

@azuenko Do you see any potential security issues with this search tool ?

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdks-documentation/5)

### CODE REVIEW

**Review by haroldcb — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdks-documentation/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @azuenko and @conord33)

**Comment by haroldcb** [comment]
It's cool that Algolia is providing some free features because they are quite expansive but so good !

**Review by conord33 — APPROVED** [review]
:lgtm: 

do you think it will work on a private repo?

> Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdks-documentation/5#-:-Mb5w5pu8Z7LVzmVslly:bidi5g1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @azuenko)

**Review by alexdisdier — COMMENTED** [review]
Yes. This is not scrapped by an external entity. 

When you build the site, a searchable index json file is created. 

So there shouldn't be any security issues, wdyt ?

> *[Reviewable](https://reviewable.io/reviews/stratumn/sdks-documentation/5#-:-Mb5xx920FCTkIICW-R0:bbrascv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @azuenko)

**Review by conord33 — APPROVED** [review]
oh cool! i would think not. unless the package itself is malicious :scream: 

> *[Reviewable](https://reviewable.io/reviews/stratumn/sdks-documentation/5#-:-Mb5zmTa5nY2RZLXz5R-:b-i5jfys)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @azuenko)

**Comment by alexdisdier** [comment]
> oh cool! i would think not. unless the package itself is malicious :scream: 
> 
> > *[Reviewable](https://reviewable.io/reviews/stratumn/sdks-documentation/5#-:-Mb5zmTa5nY2RZLXz5R-:b-i5jfys)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @azuenko)
> 
> 
> 
> 
> 

The package was recommended on the official docusaurus site so we should be safe. 😀

**Pull request merged**
