### PR TITLE
Split configuration and usage and add details about keys

### PR DESCRIPTION
**Pull request by haroldcb**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdks-documentation/2)

### CODE REVIEW

**Review by conord33 — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdks-documentation/2)* status: all files reviewed, 4 unresolved discussions (waiting on @haroldcb)

___
*[docs/configuration.mdx, line 26 at r1](https://reviewable.io/reviews/stratumn/sdks-documentation/2#-MXgAN655CIFWtAA7ZI2:-MXgAN664oIwLKYAspN5:bf6iozg) ([raw file](https://github.com/stratumn/sdks-documentation/blob/5c8ad2259c973ecc7f61f596ef8cdd27f36603c2/docs/configuration.mdx#L26)):*
> ```Markdown
>   We check that the signature and the message are valid and return an authentication token in that case.
> 
> ### Bot set up
> ```

nice good description! this is good for now. hopefully soon we can make the UI have better validation to catch poorly formatted keys....
___
*[docs/configuration.mdx, line 30 at r1](https://reviewable.io/reviews/stratumn/sdks-documentation/2#-MXgA7-vB5-lLBPwDM75:-MXgA7-vB5-lLBPwDM76:bron4oq) ([raw file](https://github.com/stratumn/sdks-documentation/blob/5c8ad2259c973ecc7f61f596ef8cdd27f36603c2/docs/configuration.mdx#L30)):*
> ```Markdown
> In order to use the SDK, you will have to create a bot in the ui.
> This bot will be linked to one team of your organisation in order to perform actions.
> You can create one bot in the organisation configuration's page : `https://account.stratumn.com/organization/bots`.
> ```

nit: typo`organisation's configuration page` :man_teacher: 
___
*[docs/usage.mdx, line 292 at r1](https://reviewable.io/reviews/stratumn/sdks-documentation/2#-MXgB0-tDFL9vD6UIlwy:-MXgB0-u1MoUBnlnmP8q:b9ui5s9) ([raw file](https://github.com/stratumn/sdks-documentation/blob/5c8ad2259c973ecc7f61f596ef8cdd27f36603c2/docs/usage.mdx#L292)):*
> ```Markdown
> - `info`: a pagination object (more on this [here](#pagination)).
> 
> To retrieve all the traces of a given stage, you can:
> ```

i think we should remove this as it is deprecated. This whole section on `getIncoming` `outgoing` `backlog`. We should probably have a deprecated section either at the root. or maybe just at the bottom of this page. maybe docusaurus has special deprecation support.
___
*[docs/usage.mdx, line 481 at r1](https://reviewable.io/reviews/stratumn/sdks-documentation/2#-MXgBafK9buSO8o0katl:-MXgBafK9buSO8o0katm:bz10tha) ([raw file](https://github.com/stratumn/sdks-documentation/blob/5c8ad2259c973ecc7f61f596ef8cdd27f36603c2/docs/usage.mdx#L481)):*
> ```Markdown
> ```
> 
> Now that there is a trace with a tag we can search for it.
> ```

i would just make this a comment like `// Add a tag to a trace` that way it is one code block in the tab. I think it make it a bit cleaner, but up to you.

**Comment by haroldcb** [comment]
___
*[docs/configuration.mdx, line 26 at r1](https://reviewable.io/reviews/stratumn/sdks-documentation/2#-MXgAN655CIFWtAA7ZI2:-MXh4bUL-ulf1QkJI2N-:b-djnyut) ([raw file](https://github.com/stratumn/sdks-documentation/blob/5c8ad2259c973ecc7f61f596ef8cdd27f36603c2/docs/configuration.mdx#L26)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

nice good description! this is good for now. hopefully soon we can make the UI have better validation to catch poorly formatted keys....
</blockquote></details>

Yes we will see with product team tomorrow :)

**Comment by haroldcb** [comment]
___
*[docs/configuration.mdx, line 30 at r1](https://reviewable.io/reviews/stratumn/sdks-documentation/2#-MXgA7-vB5-lLBPwDM75:-MXh4nZXDByXXbkhYIBi:bt2vr0x) ([raw file](https://github.com/stratumn/sdks-documentation/blob/5c8ad2259c973ecc7f61f596ef8cdd27f36603c2/docs/configuration.mdx#L30)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

nit: typo`organisation's configuration page` :man_teacher: 
</blockquote></details>

Fixed

**Comment by haroldcb** [comment]
___
*[docs/usage.mdx, line 292 at r1](https://reviewable.io/reviews/stratumn/sdks-documentation/2#-MXgB0-tDFL9vD6UIlwy:-MXh5W6s1lMFAdAMC_VL:b-2k0svc) ([raw file](https://github.com/stratumn/sdks-documentation/blob/5c8ad2259c973ecc7f61f596ef8cdd27f36603c2/docs/usage.mdx#L292)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

i think we should remove this as it is deprecated. This whole section on `getIncoming` `outgoing` `backlog`. We should probably have a deprecated section either at the root. or maybe just at the bottom of this page. maybe docusaurus has special deprecation support.
</blockquote></details>

I think for now the only deprecated methods are about transfering ownership of a trace, but we can also deprecate these methodes as it shouldn't be used anymore

**Comment by haroldcb** [comment]
___
*[docs/usage.mdx, line 481 at r1](https://reviewable.io/reviews/stratumn/sdks-documentation/2#-MXgBafK9buSO8o0katl:-MXh64IW0vI03NIzYLSy:bh95ke4) ([raw file](https://github.com/stratumn/sdks-documentation/blob/5c8ad2259c973ecc7f61f596ef8cdd27f36603c2/docs/usage.mdx#L481)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

i would just make this a comment like `// Add a tag to a trace` that way it is one code block in the tab. I think it make it a bit cleaner, but up to you. 
</blockquote></details>

You're right

**Comment by haroldcb** [comment]
___
*[docs/usage.mdx, line 481 at r1](https://reviewable.io/reviews/stratumn/sdks-documentation/2#-MXgBafK9buSO8o0katl:-MXh67HJER7WXzi4dzKA:b-896fix) ([raw file](https://github.com/stratumn/sdks-documentation/blob/5c8ad2259c973ecc7f61f596ef8cdd27f36603c2/docs/usage.mdx#L481)):*
<details><summary><i>Previously, haroldcb wrote…</i></summary><blockquote>

You're right
</blockquote></details>

Done.

**Review by conord33 — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdks-documentation/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haroldcb)

**Pull request merged**
